pipeline {
    agent any

    stages {

        stage ('Test') {
            steps {
                print('Hello world!')

                sh ''':
                    echo "test"

                    docker ps
                :'''
            }
        }

    }
}
